# Do basic release build.

name: test_release

on:
  schedule:
    - cron: '47 2 * * *'
  workflow_dispatch:
    inputs:
      args:
        type: string
        default: ''
        description: 'Extra arguments to pass to aptest.py'

jobs:

  test:
    name: test_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # This list should match default aptest.py:state.remote_github_runners,
        # because that is what is used with `--release-1`.
        os: [
                ubuntu-latest,
                windows-2022,
                macos-14,
                ]

      # Avoid cancelling of all runs after a single failure.
      fail-fast: false

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: test_release
        env:
          APTEST_args: ${{inputs.args}}
          ARTIFEX_SOFTWARE_SSH_KEY: ${{secrets.ARTIFEX_SOFTWARE_SSH_KEY}}
          PYMUPDFPRO_SETUP_SOT_KEY: ${{secrets.PYMUPDFPRO_SETUP_SOT_KEY}}
        run:
          'python aptest.py -P git: --PRO git: --LAYOUT git: --4LLM git: --PDF4LLM git: --wheelhouse-release aptest-wheelhouse-release --release-1'
      
      # Upload generated wheels, to be accessible from github Actions page.
      #
      - uses: actions/upload-artifact@v4
        with:
          path: |
              aptest-wheelhouse-release/*.whl
              aptest-wheelhouse-release/*.tar.gz
          name: artifact-${{ matrix.os }}
